version: '3.2'
services:
  database:
    image: mongo:4.4.6
    container_name: gramaddict_mongo
    restart: always
    ports:
      - 127.0.0.1:${MONGO_PORT:-27019}:27017
    volumes:
      - ./.mongodb:/data/db